version: 2.1 
jobs:
  build:
    context: AppImages
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install fuse libfuse2 kmod git jq patch appstream-util libindicator7 libdbusmenu-gtk4 nodejs
            sudo depmod
            sudo modprobe fuse
      - run:
          name: "Setting up NodeJS and Yarn"
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            echo "nvm install v12.14.0..."
            nvm install v12.14.0
            echo "nvm use v12.14.0"
            nvm use v12.14.0
            echo "npm version"
            npm version
            echo "installing yarn..."
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            yarn --version
            echo "Done."
      - run:
          name: "Preparing AppImage tools and assets"
          command: |
            mkdir bin; cd bin
            curl -L https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -o appimagetool; chmod +x appimagetool
            curl -L https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -o linuxdeploy; chmod +x linuxdeploy
            cd ..
            curl 'https://about.riot.im/images/riot-nav.svg' -o riot-nav.svg
            git clone https://github.com/vector-im/riot-web.git
            cd riot-web
            git fetch --tags
            git checkout v1.5.6
      - run:
          name: "Building Electron image"
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            export PATH="$NVM_DIR/versions/node/v12.14.0/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            nvm use v12.14.0
            echo "NodeJS Version $(nodejs -v) is installed."
            cd riot-web
            patch -i ../package.json.patch
            cp config.sample.json config.json
            yarn install
            yarn add electron-builder --dev
            yarn build:electron:appimage
            cd ..
      - run:
          name: "Building and uploading AppImage"
          command: |
            echo $SIGN_CERT > certificate.asc
            gpg --import ./certificate.asc
            ./riot-web/electron_app/dist/Riot-*.AppImage --appimage-extract
            mv squashfs-root AppDir
            cd AppDir
            mkdir -p usr/share/metainfo
            mkdir -p usr/share/icons/hicolor/scalable/apps
            mkdir -p usr/share/applications
            cp ../riot-nav.svg usr/share/icons/hicolor/scalable/apps
            cp ../im.vector.riot-web.appdata.xml usr/share/metainfo
            cp riot-web.desktop usr/share/applications
            cd ..
            export SIGN=1
            export ARCH=x86_64
            export UPDATE_INFORMATION="gh-releases-zsync|zilti|riot-web.AppImage|continuous|Riot-*.AppImage.zsync"
            bin/linuxdeploy --appdir=AppDir --desktop-file=AppDir/riot-web.desktop --icon-file=AppDir/usr/share/icons/hicolor/scalable/apps/riot-nav.svg -oappimage
            export TRAVIS_REPO_SLUG="zilti/riot-web.AppImage"
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh *.AppImage*
